bootstrapServers: "<CLUSTER_NAME>.apps.eu46a.prod.ole.redhat.com:443"
sslTruststoreLocation: "/home/pplaczek/AD482/truststore.jks"
sslTruststorePassword: "password"
postgresAddress: "jdbc:postgresql://127.0.0.1:5488/my_data_wh_db"
postgresUsername: "my_data_wh_user"
postgresPassword: "my_data_wh_pwd"